# Generated by Django 5.2.3 on 2025-06-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(choices=[('Card1', 'Card 1'), ('Card2', 'Card 2'), ('Card3', 'Card 3'), ('Card4', 'Card 4')], max_length=10, unique=True),
        ),
    ]
