# Generated by Django 5.2.3 on 2025-06-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
