# Generated by Django 5.2.3 on 2025-06-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_current_date_alter_humidity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
